function r = rotor(I, J, omega, s, sdot, b)

% Calculate the ith component of the moment generated by a spinning rotor
%     - J/I(ii)*(sdot(1)*b1(1) - s(1)*(b2(1)*omega(3) - b3(1)*omega(2))) ...
%     - J/I(ii)*(sdot(2)*b1(2) - s(2)*(b2(2)*omega(3) - b3(2)*omega(2))) ...
%     - J/I(ii)*(sdot(3)*b1(3) - s(3)*(b2(3)*omega(3) - b3(3)*omega(2)))


% Single rotor, constant orientation, constant spin:

%     r = [J/I(1)*( s*(b(2)*omega(3) - b(3)*omega(2)) );
%          J/I(2)*( s*(b(3)*omega(1) - b(1)*omega(3)) );
%          J/I(3)*( s*(b(1)*omega(2) - b(2)*omega(1)) )];
% Single rotor, constant orientation, variable spin:

    r = [-J/I(1)*( sdot*b(1) - s*(b(2)*omega(3) - b(3)*omega(2)) );
         -J/I(2)*( sdot*b(2) - s*(b(3)*omega(1) - b(1)*omega(3)) );
         -J/I(3)*( sdot*b(3) - s*(b(1)*omega(2) - b(2)*omega(1)) )];
    
% For any rotor, variable orientation, variable spin: VALIDATE
%     r = [-J/I(1)*( sddot*b(1) + sdot*bdot(1) - s*(b(2)*omega(3) - b(3)*omega(2)) );
%          -J/I(2)*( sddot*b(2) + sdot*bdot(2) - s*(b(3)*omega(1) - b(1)*omega(3)) );
%          -J/I(3)*( sddot*b(3) + sdot*bdot(3) - s*(b(1)*omega(2) - b(2)*omega(1)) )];
    
end